### ISSUE TITLE
No such file or directory: 'weights.tar'

### ISSUE THREAD

**Issue by Recialhot** [SlimeVRX/FID#2]
Hello, thank you for your work. I would like to check if the code I installed is correct, but there is no weights.tar, so I cannot directly evaluate it. It seems that your expression can directly test the results of your paper using weights.tar, but I cannot find the corresponding file. Do you have it?

**Comment by SlimeVRX** [comment]
Sorry, I don't have weights.tar file.

**Comment by SlimeVRX** [comment]
I just discovered that there is a newly released paper also called FIP, with a different author, with source code, you can refer to it

Name: Fast Human Motion reconstruction from sparse inertial measurement units considering the human shape (FIP)

Paper: https://www.nature.com/articles/s41467-024-46662-5

Source: https://github.com/bachongyou/FIP_inference

**Comment by Recialhot** [comment]
> 我刚刚发现有一篇新发表的论文也叫FIP，作者不同，有源码，可以参考
> 
> 名称：考虑人体形状的稀疏惯性测量单元的快速人体运动重建 （FIP）
> 
> 论文：https://www.nature.com/articles/s41467-024-46662-5
> 
> 来源： https://github.com/bachongyou/FIP_inference

thanks,i will see it

**Comment by Recialhot** [comment]
> 对不起，我没有weights.tar文件。

hello, when i run train.py, it will cause this probelm, that's why? thank you

batch_size == 128
model == RNN
fineturning == False
cuda == True
resume == 
evaluate == False
workers == 4
half == False
lr == 0.0005
weight_decay == 0
save_freq == 30
save_dir == save_pose
start_epoch == 0
epochs == 300
visdom == False
train len 150, vail len150
  0%|                                                   | 0/150 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/HDD2/yanshiqi/FDIP_code/FDIP/train.py", line 287, in <module>
    main()
  File "/home/HDD2/yanshiqi/FDIP_code/FDIP/train.py", line 270, in main
    train_loss = train(train_loader, model, criterion, optimizers, epoch, args.fineturning)
  File "/home/HDD2/yanshiqi/FDIP_code/FDIP/train.py", line 87, in train
    output = model.forward_my((imu, leaf_jtr, full_jtr), refine=refine)            
  File "/home/HDD2/yanshiqi/FDIP_code/FDIP/net.py", line 114, in forward_my
    global_reduced_pose = self.pose_net.forward(imu)[0]
  File "/home/HDD2/yanshiqi/FDIP_code/FDIP/net.py", line 20, in forward
    x, h = self.rnn(self.dropout(relu(self.linear1(x))), h)
  File "/home/HDD2/yanshiqi/.conda/envs/avatarjlm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/HDD2/yanshiqi/.conda/envs/avatarjlm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/HDD2/yanshiqi/FDIP_code/FDIP/sru/modules.py", line 634, in forward
    h, c = rnn(prevx, c0_[i], mask_pad=mask_pad)
  File "/home/HDD2/yanshiqi/.conda/envs/avatarjlm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/HDD2/yanshiqi/.conda/envs/avatarjlm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/HDD2/yanshiqi/FDIP_code/FDIP/sru/modules.py", line 276, in forward
    h, c = self.apply_recurrence(U, V, residual, c0, scale_val, mask_c, mask_pad)
  File "/home/HDD2/yanshiqi/FDIP_code/FDIP/sru/modules.py", line 298, in apply_recurrence
    return elementwise_recurrence_gpu(U, residual, V, self.bias, c0,
  File "/home/HDD2/yanshiqi/FDIP_code/FDIP/sru/ops.py", line 129, in elementwise_recurrence_gpu
    return ElementwiseRecurrence.apply(
  File "/home/HDD2/yanshiqi/.conda/envs/avatarjlm/lib/python3.9/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/HDD2/yanshiqi/FDIP_code/FDIP/sru/cuda_functional.py", line 176, in forward
    h, last_hidden, c = elementwise_recurrence_forward(
RuntimeError: Caught an unknown exception!
ERROR conda.cli.main_run:execute(41): `conda run python /home/HDD2/yanshiqi/FDIP_code/FDIP/train.py -c -b 128 --epochs 300 --save-dir save_pose --lr 5e-4 -m RNN` failed. (See above for error)

**Comment by SlimeVRX** [comment]
@Recialhot Sorry! I can't check errors for you at the moment.
